title: wix-grow-setup-tooling
description: Setting-up your machine/environment
template:
  repo: wix-grow-setup-tooling-template
  name: wix-grow-setup-tooling
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
